
# name_style_in_rpg_binary: name_style_in_rpg_netcdf
FileCode: file_code
HeaderLen: header_length
CGProg: program_number
ModelNo: model_number
Freq: radar_frequency
AntSep: antenna_separation
AntDia: antenna_diameter
AntG: antenna_gain
HPBW: half_power_beam_width
Cr: radar_constant
DualPol: dual_polarisation
CompEna: compression
AntiAlias: anti_alias
SampDur: sample_duration
GPSLat: gps_latitude
GPSLong: gps_longitude
CalInt: calibration_interval
RAltN: n_range_layers
TAltN: n_temperature_layers
HAltN: n_humidity_layers
SequN: n_chirp_sequences
RAlts: range_layers
Fr: range_factors
SpecN: n_samples_in_chirp
RngOffs: chirp_start_indices
ChirpReps: n_chirps_in_sequence
SeqIntTime: integration_time
dR: range_resolution
MaxVel: nyquist_velocity
ChanBW: bandwidth
ChirpLowIF: lowest_IF_frequency
ChirpHighIF: highest_IF_frequency
RangeMin: minimum_altitude
RangeMax: maximum_altitude
ChirpFFTSize: fft_size
ChirpInvSamples: n_invalid_samples
ChirpCenterFr: chirp_center_frequency
ChirpBWFr: chirp_bandwidth
FFTStartInd: fft_start_index
FFTStopInd: fft_stop_index
ChirpFFTNo: n_chirp_fft
SampRate: adc_sampling_rate
MaxRange: maximum_range
SupPowLev: power_leveling_flag
SpkFilEna: spike_filter_flag
PhaseCorr: phase_correction_flag
RelPowCorr: relative_power_correction_flag
FFTWindow: fft_window
FFTInputRng: adc_voltage_range
SWVersion: software_version
NoiseFilt: noise_filter_threshold
velocity_vectors: velocity_vectors
MSec: time_ms
QF: quality_flag
RR: rain_rate
RelHum: relative_humidity
EnvTemp: temperature
BaroP: pressure
WS: wind_speed
WD: wind_direction
DDVolt: voltage
DDTb: brightness_temperature
LWP: lwp
PowIF: IF_power
Elev: elevation
Azi: azimuth
Status: status_flag
TransPow: transmitter_power
TransT: transmitter_temperature
RecT: receiver_temperature
PCT: pc_temperature
TotSpec: doppler_spectrum
SLv: sensitivity_limit_v
HSpec: doppler_spectrum_h
ReVHSpec: covariance_spectrum_re
ImVHSpec: covariance_spectrum_im
SLh: sensitivity_limit_h  
HNoisePow: integrated_noise_h
